language: node_js
cache: yarn
node_js:
  - node
  - "10"
  - "8"
os:
  - linux
  - osx
branches:
  only:
    - master
script:
  - skip test
jobs:
  include:
    - stage: release
      if: branch IN (master, next)
      node_js: node
      script:
        - npx semantic-release
      env:
